import scrapy

class Product(scrapy.Item):
    Office_address = scrapy.Field()
    phone_number_office = scrapy.Field()
    Residential_address_1 = scrapy.Field()
    phone_number_residential_1 = scrapy.Field()
    Residential_address_2 = scrapy.Field()
    phone_number_residential_2 = scrapy.Field()
    Residential_address_3 = scrapy.Field()
    phone_number_residential_3 = scrapy.Field()
    Residential_address_4 = scrapy.Field()
    phone_number_residential_4 = scrapy.Field()
    Residential_address_5 = scrapy.Field()
    phone_number_residential_5 = scrapy.Field()
    Residential_address_6 = scrapy.Field()
    phone_number_residential_6 = scrapy.Field()
    passport_no = scrapy.Field()
    gender = scrapy.Field()
    national_id = scrapy.Field()
    date_of_birth = scrapy.Field()
    marital_status = scrapy.Field()
    nationality = scrapy.Field()
    salary = scrapy.Field()
    branch_name = scrapy.Field()
    Current_Organisation = scrapy.Field()
    Previous_Organisation = scrapy.Field()
    Emirates_ID_Expiry_Date = scrapy.Field()
    Visa_Expiry_Date = scrapy.Field()
    Passport_Expiry_Date = scrapy.Field()
    Date_of_joining = scrapy.Field()
    cif_cid = scrapy.Field()
    card_number = scrapy.Field()
    total_amount_overdue = scrapy.Field()
    Total_Balance_Outstanding = scrapy.Field()
    scrape_date = scrapy.Field()
